### PR TITLE
Fix #630 - Project status update.

### LINKED ISSUE #630: Move to new repository
@wargio

As NBS-System does not seem to have any interest in continuing development on naxsi, I suggest making a PR:
* moving current readme as old
* making a new readme clearly stating explicitly to check your repository https://github.com/wargio/naxsi

If you create the PR, I'll try to confirm with the team that they clearly don't plan on investing any on that project, and agree to merge it. That should probably help... that is if you want to continue working on the project (which seems to be the case, as your repo is still getting some commit, and I have not seen anyone else do anything in years here)

### PR DESCRIPTION
**Pull request by wargio**
Fix #630

@ze42 Let me know if any changes are required. if needed i can add also a link to whatever the sales team wants.

### CODE REVIEW

**Comment by wargio** [comment]
@ze42 any news?

**Comment by ze42** [comment]
Still no formal go, but going in the right way.
N+2 ok with it, waiting a go from higher up.

And... ending my work at NBS, but someone else got ownership of nbssystem, so they might actually validate it once they do get the validation...

**Comment by wargio** [comment]
@ze42 thank you for this.

**Comment by wargio** [comment]
@mremande any update?

**Pull request merged**
