### PR TITLE
Create scratch area for header lowercasing.

### PR DESCRIPTION
**Pull request by marcelomd**
Should solve #227 and #294.

### CODE REVIEW

**Comment by buixor** [comment]
hey :)

Thanks for the MR, but I'd like to limit alloc/string copies in a piece of code that is called that often.
I'd keep this one at hand, because, while it seems to work, I hope we can find a "cheaper" way ;p

**Comment by marcelomd** [comment]
Yeah, I know =D

It's not pretty and will degrade performance, same thinking here. But since we needed Naxsi+HTTP/2 "for yesterday", as we say here, I figured I'd try a quick fix and buy some time to dig deeper into it.

I'm sharing in case anyone wishes to take the performance hit anyway. Maybe a warning in the commit message. Whichever you decide, to merge or not, is great. We're glad to help =)

**Comment by buixor** [comment]
and I thank you a lot for that ;)

**Comment by buixor** [comment]
Mh I didn't had much time to properly work on the topic, but so far I didn't see any better alternatives :/

**Comment by marcelomd** [comment]
Hey,
We also couldn't think of anything better. Sorry about that.
We thought about copying the whole header area and working only there. However, this has its own drawbacks.
Another idea was to patch Nginx's HTTP/2 module. I doubt the Nginx guys would approve hehehe.

**Pull request merged**
