### PR TITLE
Http2

### PR DESCRIPTION
**Pull request by jiaxinghui**

### CODE REVIEW

**Comment by hogze94** [comment]
Whats the status of this?

**Comment by buixor** [comment]
Hello,

It will be merged in for 0.56, which should be in the coming months.
However, some users are actively using http2, and did not report issues.

**Comment by michal-grabowski** [comment]
Is there any schedule for 0.56 release? I'd like to start using naxsi on my production server but because of http2 but i'm still waiting for fixed release.

**Comment by buixor** [comment]
Such Impatience :D Just kidding, I'm trying to book some time to work on naxsi in the upcoming weeks, I have a few extra issues to deal with before the merge.

**Comment by michal-grabowski** [comment]
Please don't get me wrong, i'm just excited about NAXSI and would love to use it. Fingers crossed. Thanks.

**Comment by Doemela** [comment]
I use nginx 1.13.4 OpenSSL 1.0.2l debian jessie with +13 domains with naxsi http2 without any problems

**Pull request merged**
