### PR TITLE
Reformat

### PR DESCRIPTION
**Pull request by karnauskas**
Formating code with vscode/clang, removing some whitespaces.

### CODE REVIEW

**Comment by buixor** [comment]
Hello,

Sorry totally missed that one, trying to review asap.

**Comment by buixor** [comment]
Hello,

Sorry missed that one, trying to start a review :)

**Comment by jvoisin** [comment]
The right way™ to enforce a coding style would be to submit a script to do it, instead of expecting a thorough review of `+5,088 −4,855` lines of code that don't add any user-facing value :/

**Comment by sabban** [comment]
Unless a script is provided, and proves itself useful this PR will be closed.

**Pull request closed without merging**
